server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insta_clone?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace # bind 쿼리의 내용까지 출력. ? 부분이 실제 값으로 표현됨